[versions]
arrowkt = "1.2.4"
jvmTarget = "21"
kotlin = "2.0.0"
spotless = "6.25.0"
springDependencyManagement = "1.1.6"
springboot = "3.3.2"

[libraries]

kotlin_core = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin_jackson_module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin_reflection = { module = "org.jetbrains.kotlin:kotlin-reflect" }
springboot_web_starter = { module = "org.springframework.boot:spring-boot-starter-web" }
arrowkt_core = { module = "io.arrow-kt:arrow-core", version.ref = "arrowkt" }

[plugins]

kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springboot_dependency_management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

[bundles]

kotlin_all = [
    "kotlin_core",
    "kotlin_jackson_module",
    "kotlin_reflection",
]

springboot_all = [
    "springboot_web_starter",
]
