name: Continuous Integration

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: yonatankarp/github-actions/.github/workflows/ci.yml@v1
    with:
      app_name: ${{ matrix.service }}
      context: .
      build_dockerfile: false

  dependabot_auto_merge:
    needs: pipeline
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1
    secrets:
      GITHUB_PAT: ${{ secrets.REVIEWER_GITHUB_TOKEN }}

  linters:
    uses: yonatankarp/github-actions/.github/workflows/linters.yml@v1
